### ISSUE TITLE
API deprecation warnings on kubecfg update --gc-tag

### ISSUE THREAD

**Issue by muxmuse** [kubecfg/kubecfg#30]
I receive API deprecation warnings when running `kubecfg update --gc-tag`. The warnings do not appear without the `--gc-tag` flag. Can kubecfg be configured to not query deprecated APIs?

**Comment by anguslees** [comment]
Yep, this is a long-standing optimisation (thanks to qbec for first describing this improvement).

Currently kubecfg garbage collects objects through _each_ of the api versions in which a stale object appears.  We only need to delete it through one api version - and we may as well pick a recent/recommended version, which would avoid the deprecation warning you're seeing.
