### ISSUE TITLE
Cut new release

### ISSUE THREAD

**Issue by mkmik** [kubecfg/kubecfg#419]
We recently merged a new feature that some users may find useful: https://github.com/kubecfg/kubecfg/pull/415

CC: @charlesthomas 

A few other automated dependency bumps landed since the last release.
We need to quickly skim through the commits since the last review and compose a meaningful changelog

**Comment by jdockerty** [comment]
I believe [`v0.34.3`](https://github.com/kubecfg/kubecfg/releases/tag/v0.34.3) with notes should satisfy this :rocket:
