### ISSUE TITLE
kubecfg diff behaviour is changed/broken?

### ISSUE THREAD

**Issue by gaurav517** [kubecfg/kubecfg#56]
Is there a breaking change in kubecfg-diff? Latest version show different output (not making much sense) than in v0.22.0.

**Comment by primeroz** [comment]
Do you have an example of this change ? thanks

**Comment by mkmik** [comment]
In the last release we did update a bunch of dependencies which may have caused a regression. Details would be very helpful indeed

**Comment by prahaladramji** [comment]
Here's a simple example comparing the behaviour between 2 versions.

### Applied YAML
```yaml
apiVersion: v1
kind: Namespace
metadata:
  annotations: {}
  labels:
    istio-injection: enabled
    name: cerebro
  name: cerebro
```

### kubecfg diff command
```bash
kubecfg  diff --diff-strategy=subset test.jsonnet
```

### Current result
All versions from the first release (v0.23.0) in [this repo](https://github.com/kubecfg/kubecfg/releases) have this broken behaviour.
```
kubecfg version: v0.24.1
jsonnet version: v0.18.0
client-go version: v0.0.0-master+$Format:%H$
```
output
```
---
- live namespaces cerebro
+ config namespaces cerebro
  {
-   "apiVersion": "v1",
    "kind": "Namespace",
+ {
    "metadata": {
+ {
      "annotations": {},
+ {
      "labels": {
+ {
        "istio-injection": "enabled",
+ {
        "name": "cerebro"
+ {
      },
- {
+   "apiVersion": "v1",
- {
+   "apiVersion": "v1",
  {
- {
+   "apiVersion": "v1",
    "apiVersion": "v1",
+   }
+ }
```

### Expected
this is the last release from the [vmware archive](https://github.com/vmware-archive/kubecfg/releases/tag/v0.22.0)
```
kubecfg version: v0.22.0
jsonnet version: v0.17.0
client-go version: v0.0.0-master+$Format:%h$
```
output
```
---
- live namespaces cerebro
+ config namespaces cerebro
namespaces cerebro unchanged
```

**Comment by mkmik** [comment]
thank you; a fix is in flight in https://github.com/kubecfg/kubecfg/pull/58; just need to write tests. sorry for the regression; that's what happens when you don't have tests and enable automated dependency update bots.
